name: Deploy

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v0.1.10

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@v0.1.10
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/app/Bot-Hippo"

    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.10
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
            sudo /bin/systemctl restart hippobot.service
            cd /app/Bot-Hippo
            node deploy-commands-w9.js
            node deploy-commands-cc.js
